package default_package;

import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;

public class FunctionsClientConsumer {
    public static void main(String[] args) throws Exception_Exception {
        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();

        // Use the URL defined in the soap address portion of the WSDL
        factory.setAddress("http://localhost:8080/soapserver2.0/services/FunctionsClientPort?wsdl");

        // Utilize the class which was auto-generated by Apache CXF wsdl2java
        factory.setServiceClass(FunctionsClient.class);

        Object client = factory.create();

        try {

            // Call the Web Service to perform an operation

            ((FunctionsClient)client).comeca();
        } catch (SecurityException e) {

            e.printStackTrace();

        } catch (IllegalArgumentException e) {

            e.printStackTrace();

        }
    }
}
